# Markdownlint configuration
# See https://github.com/DavidAnson/markdownlint for rules

# Default state for all rules
default: true

# MD013/line-length – increase allowed length and keep table exceptions
MD013:
  line_length: 250          # allow longer lines (e.g., long tables or code snippets)
  heading_line_length: 250
  code_block_line_length: 250
  code_blocks: false
  tables: false
  headings: true
  strict: false

# MD033/no-inline-html – keep allowed HTML elements
MD033:
  allowed_elements: [br, p, details, summary]

# MD041/first-line-heading – disabled (first line may not be a top‑level heading)
MD041: false

# MD046/code-block-style – enforce fenced code blocks
MD046:
  style: fenced

# **New**: Disable table column style warnings (MD060) which were causing many
# alignment errors across README and docs tables.
MD060: false
